# Generated by Django 6.0.5 on 2026-05-26 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('row_count_total', models.IntegerField(default=0)),
                ('row_count_success', models.IntegerField(default=0)),
                ('row_count_failed', models.IntegerField(default=0)),
                ('error_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='emissions.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=20)),
                ('plant_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'plant_code')},
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('raw_row', models.JSONField()),
                ('source_row_number', models.IntegerField(null=True)),
                ('activity_date', models.DateField()),
                ('activity_description', models.CharField(max_length=500)),
                ('scope', models.CharField(choices=[('S1', 'Scope 1'), ('S2', 'Scope 2'), ('S3', 'Scope 3'), ('UK', 'Unknown')], default='UK', max_length=2)),
                ('quantity_original', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_original', models.CharField(max_length=50)),
                ('quantity_normalized', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('unit_normalized', models.CharField(blank=True, max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('emission_factor_used', models.CharField(blank=True, max_length=200)),
                ('sap_plant_code', models.CharField(blank=True, max_length=20)),
                ('sap_material_group', models.CharField(blank=True, max_length=20)),
                ('sap_vendor', models.CharField(blank=True, max_length=50)),
                ('sap_po_number', models.CharField(blank=True, max_length=20)),
                ('utility_meter_id', models.CharField(blank=True, max_length=100)),
                ('utility_tariff', models.CharField(blank=True, max_length=100)),
                ('utility_billing_start', models.DateField(blank=True, null=True)),
                ('utility_billing_end', models.DateField(blank=True, null=True)),
                ('travel_segment_type', models.CharField(blank=True, max_length=20)),
                ('travel_origin', models.CharField(blank=True, max_length=10)),
                ('travel_destination', models.CharField(blank=True, max_length=10)),
                ('travel_traveler_email', models.CharField(blank=True, max_length=200)),
                ('travel_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged — Needs Attention'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.tenant')),
            ],
            options={
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['tenant', 'scope', 'review_status'], name='emissions_e_tenant__5d8b85_idx'), models.Index(fields=['tenant', 'source_type', 'activity_date'], name='emissions_e_tenant__445f95_idx'), models.Index(fields=['ingestion_job', 'is_suspicious'], name='emissions_e_ingesti_80712e_idx')],
            },
        ),
    ]
